# Generated by Django 3.1.4 on 2021-02-18 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XmlDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('xmldocument', models.FileField(upload_to='xml/documents/%Y%m%d%M%S')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dcc_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dcc.dccusers')),
            ],
        ),
    ]
