# Generated by Django 3.1.4 on 2021-02-14 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XmlDocuments',
        ),
    ]
